spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC"
    username: redd
    password: redd
  main:
    allow-circular-references: true
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
  mvc.hiddenmethod.filter.enabled: true

